In [5]:
import numpy as np

In [4]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
def nat():
    current_number = 0
    while True:
        yield current_number
        current_number += 1

In [5]:
numbers = nat()

In [9]:
next(numbers)

3

In [10]:
def factorials():
    natural_numbers = nat()
    current_number = next(natural_numbers)
    result = 1
    while True:
        yield result
        current_number = next(natural_numbers)
        result *= current_number

In [12]:
# Only prints the factorials
for n, n_factorial in enumerate(factorials()):  
    print(f"{n}!=", n_factorial)
    if n_factorial >= 100000000000000:
        break

0!= 1
1!= 1
2!= 2
3!= 6
4!= 24
5!= 120
6!= 720
7!= 5040
8!= 40320
9!= 362880
10!= 3628800
11!= 39916800
12!= 479001600
13!= 6227020800
14!= 87178291200
15!= 1307674368000
16!= 20922789888000
17!= 355687428096000


In [22]:
def fibonacci():
    a, b = 0, 1

    while True:
        yield a
        a, b = b, a + b

In [23]:
for fib in fibonacci():
    print(fib, end=" ")
    if fib >= 100000:
        break

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 

## Matrices

In [6]:
A = np.array([
[2, 3, 7],
[8, 9, 1]
])

B = np.array([
[1, -3, 0],
[2, -4, 1]
])


In [8]:
A.T

array([[2, 8],
       [3, 9],
       [7, 1]])

In [9]:
A + B

array([[ 3,  0,  7],
       [10,  5,  2]])

In [10]:
A + A

array([[ 4,  6, 14],
       [16, 18,  2]])

In [11]:
2 * A

array([[ 4,  6, 14],
       [16, 18,  2]])

In [13]:
2 * A + 5 * B   # linear combination

array([[ 9, -9, 14],
       [26, -2,  7]])

In [15]:
B.T

array([[ 1,  2],
       [-3, -4],
       [ 0,  1]])

In [16]:
B.T.shape

(3, 2)

In [17]:
A.dot(B.T)

array([[ -7,  -1],
       [-19, -19]])

In [18]:
A * B # Hadamard product, element-wise

array([[  2,  -9,   0],
       [ 16, -36,   1]])

In [20]:
A @ B.T # @ = dot()

array([[ -7,  -1],
       [-19, -19]])