In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Calculus

### Live Demos

In [2]:
def get_limit(f, a):
    epsilon = np.array([
        10 ** p
        for p in np.arange(0, -11, -1, dtype = float)])
    x = np.append(a - epsilon, (a + epsilon)[::-1])
    y = f(x)
    return np.stack([x, y], axis = 1)

In [3]:
get_limit(lambda x: x ** 2, 3)

array([[ 2.        ,  4.        ],
       [ 2.9       ,  8.41      ],
       [ 2.99      ,  8.9401    ],
       [ 2.999     ,  8.994001  ],
       [ 2.9999    ,  8.99940001],
       [ 2.99999   ,  8.99994   ],
       [ 2.999999  ,  8.999994  ],
       [ 2.9999999 ,  8.9999994 ],
       [ 2.99999999,  8.99999994],
       [ 3.        ,  8.99999999],
       [ 3.        ,  9.        ],
       [ 3.        ,  9.        ],
       [ 3.        ,  9.00000001],
       [ 3.00000001,  9.00000006],
       [ 3.0000001 ,  9.0000006 ],
       [ 3.000001  ,  9.000006  ],
       [ 3.00001   ,  9.00006   ],
       [ 3.0001    ,  9.00060001],
       [ 3.001     ,  9.006001  ],
       [ 3.01      ,  9.0601    ],
       [ 3.1       ,  9.61      ],
       [ 4.        , 16.        ]])

In [4]:
np.arange(0, -11, -1, dtype = float)

array([  0.,  -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.])

In [5]:
10 ** np.arange(0, -11, -1, dtype = float)

array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08, 1.e-09, 1.e-10])

In [6]:
def calculate_derivative(f, a, h = 1e-7):
    return (f(a + h) - f(a)) / h

In [8]:
print(
    calculate_derivative(
        lambda x: 3 * x**2 + 5 * x - 8, 3)
)

23.00000026878024


In [10]:
x_old = 0
x_new = 6
step_size = 0.01
precision = 0.00001

def df(x):
    # f'(x^4 - 3x^3 + 2) = 4x^3 - 9x^2
    y = 4 * x ** 3 - 9 * x ** 2
    return y

while abs(x_new - x_old) > precision:
    x_old = x_new
    x_new += -step_size * df(x_old)
print("The local minimum occurs at ", x_new)

The local minimum occurs at  2.2499646074278457
